service:
  name: ${self:custom.NAME}

frameworkVersion: ">=2.68.0"

useDotenv: true

variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  stage: ${self:custom.STAGE}

custom:
  NAME: keep-learning-tokyo-lambda
  STAGE: ${file(./configs/env.js):exporter.STAGE}
  BASE_URL: ${file(./configs/env.js):exporter.BASE_URL}
  ENDPOINT_ENV: ${file(./configs/env.js):exporter.ENDPOINT_ENV}
  NODE_ENV: ${file(./configs/env.js):exporter.NODE_ENV}

# 少しでもデプロイのパッケージファイルを少なくする
package:
  excludeDevDependencies: true
  exclude:
    - .**
    - .**/*
    - .nuxt/dist/client
    - app/**
    - scripts/**
    - LICENSE
    - README.md
    - package.json
    - yarn.lock
    # Node.js 上で使われないモジュール
    # 重いものを優先的に除外
    - node_modules/eslint**/**
    - node_modules/babel**/**
    - node_modules/caniuse-db/**
    - node_modules/prettier/**
    - node_modules/vuetify/**
    - node_modules/@fortawesome/**
    - node_modules/sass/**
    - node_modules/@mdi/**
    - node_modules/json-refs/**
    - node_modules/node-sass/**
    - node_modules/moment/**
    - node_modules/yargs/**
    - node_modules/xxhashjs/**
    - node_modules/jschardet/**
    - node_modules/**/*.md
    - node_modules/**/bin/**
  include:
    - server/**
    - configs/**
    - nuxt.config.js
    - .nuxt/**
    - node_modules/autoprefixer/**
    - node_modules/babel-runtime/**
    - node_modules/babel-extract-comments/**


functions:
  render:
    handler: server/handler.render
    timeout: 30
    memorySize: 2048
    # provisionedConcurrency: 5
    environment:
      BASE_URL: ${self:custom.BASE_URL}
      ENDPOINT_ENV: ${self:custom.ENDPOINT_ENV}
      NODE_ENV: ${self:custom.NODE_ENV}
      VUE_APP_CTF_SPACE_ID: ${env:VUE_APP_CTF_SPACE_ID}
      VUE_APP_CTF_CDA_ACCESS_TOKEN: ${env:VUE_APP_CTF_CDA_ACCESS_TOKEN}
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get
